version: '{build}'

branches:
  only:
    - master

environment:
  matrix:
#    - JAVA_HOME: C:\Program Files\Java\jdk1.6.0
#      PATH: C:\Program Files\Java\jdk1.6.0\bin;%PATH%
#    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
#      PATH: C:\Program Files\Java\jdk1.7.0\bin;%PATH%
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      PATH: C:\Program Files\Java\jdk1.8.0\bin;%PATH%

build_script:
  - java -Xmx32m -version
  - javac -J-Xmx32m -version
  - .\mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - .\mvnw test -B
